const Inspection = require('../models/Inspection');
const Institution = require('../models/Institution');
const Inspector = require('../models/Inspector');
const { haversineDistance } = require('../utils/haversine');
const { getSocket } = require('../services/socketService');
const { logAction } = require('../services/auditService');
const notificationController = require('./notificationController');
const User = require('../models/User');

exports.getInspections = async (req, res, next) => {
  try {
    let filter = {};
    if (req.user.role === 'INSPECTOR') {
      const inspector = await Inspector.findOne({ userId: req.user._id });
      if (inspector) filter.inspectorId = inspector._id;
      else return res.status(200).json([]);
    }
    const data = await Inspection.find(filter).populate('institutionId').populate({ path: 'inspectorId', populate: { path: 'userId', select: 'name email' } });
    res.status(200).json(data);
  } catch (error) { next(error); }
};
exports.getInspectionById = async (req, res, next) => {
  try {
    const data = await Inspection.findById(req.params.id).populate('institutionId').populate({ path: 'inspectorId', populate: { path: 'userId', select: 'name email' } });
    if (!data) return res.status(404).json({ message: 'Not found' });
    res.status(200).json(data);
  } catch (error) { next(error); }
};
exports.createInspection = async (req, res, next) => {
  try {
    const data = await Inspection.create(req.body);
    await data.populate('institutionId');
    res.status(201).json(data);
  } catch (error) { next(error); }
};
exports.updateInspection = async (req, res, next) => {
  try {
    const data = await Inspection.findByIdAndUpdate(req.params.id, req.body, { new: true });
    res.status(200).json(data);
  } catch (error) { next(error); }
};
exports.deleteInspection = async (req, res, next) => {
  try { await Inspection.findByIdAndDelete(req.params.id); res.status(200).json({ message: 'Deleted' }); } catch (error) { next(error); }
};
exports.createSurpriseInspection = async (req, res, next) => {
  try {
    const insts = await Institution.find({ status: 'ACTIVE' });
    if (!insts.length) return res.status(400).json({ message: 'No institutions' });
    const inst = insts[Math.floor(Math.random() * insts.length)];
    const inspectors = await Inspector.find({ availability: true }).populate('userId', 'name');
    if (!inspectors.length) return res.status(400).json({ message: 'No inspectors' });
    const insp = inspectors[Math.floor(Math.random() * inspectors.length)];
    const inspection = await Inspection.create({
      institutionId: inst._id,
      inspectorId: insp._id,
      type: 'SURPRISE',
      status: 'ASSIGNED',
      assignedAt: new Date(),
      reason: 'Surprise inspection generated by system'
    });
    insp.workload += 1;
    await insp.save();
    getSocket().emit('inspection_assigned', { inspectionId: inspection._id });
    await notificationController.createNotification(
      insp.userId._id,
      'New Surprise Inspection',
      `You have been assigned a surprise inspection at ${inst.name}`,
      'INSPECTION_ASSIGNED',
      { inspectionId: inspection._id }
    );
    res.status(201).json({ inspectionId: inspection._id, institution: inst.name, inspector: insp.userId.name });
  } catch (error) { next(error); }
};
exports.verifyGPS = async (req, res, next) => {
  try {
    const { latitude, longitude } = req.body;
    const inspection = await Inspection.findById(req.params.id).populate('institutionId');
    if (!inspection) return res.status(404).json({ message: 'Not found' });
    const inspector = await Inspector.findOne({ userId: req.user._id });
    if (!inspector || inspection.inspectorId.toString() !== inspector._id.toString()) {
      return res.status(403).json({ message: 'Not assigned' });
    }
    const inst = inspection.institutionId;
    const distance = haversineDistance(latitude, longitude, inst.latitude, inst.longitude);
    const verified = distance <= 100;
    inspection.latitude = latitude;
    inspection.longitude = longitude;
    inspection.gpsVerified = verified;
    inspection.gpsVerifiedAt = new Date();
    await inspection.save();
    getSocket().emit('gps_verified', { inspectionId: inspection._id, verified });
    res.status(200).json({ verified, distance: Math.round(distance) });
  } catch (error) { next(error); }
};
exports.startInspection = async (req, res, next) => {
  try {
    const inspection = await Inspection.findById(req.params.id);
    if (!inspection) return res.status(404).json({ message: 'Not found' });
    const inspector = await Inspector.findOne({ userId: req.user._id });
    if (!inspector || inspection.inspectorId.toString() !== inspector._id.toString()) {
      return res.status(403).json({ message: 'Not assigned' });
    }
    if (!inspection.gpsVerified) return res.status(400).json({ message: 'GPS not verified' });
    if (!['ASSIGNED','ACCEPTED'].includes(inspection.status)) return res.status(400).json({ message: 'Invalid status' });
    inspection.status = 'IN_PROGRESS';
    inspection.startedAt = new Date();
    await inspection.save();
    getSocket().emit('inspection_started', { inspectionId: inspection._id });
    res.status(200).json({ message: 'Started' });
  } catch (error) { next(error); }
};
exports.updateChecklist = async (req, res, next) => {
  try {
    const { checklist } = req.body;
    const inspection = await Inspection.findById(req.params.id);
    if (!inspection) return res.status(404).json({ message: 'Not found' });
    const inspector = await Inspector.findOne({ userId: req.user._id });
    if (!inspector || inspection.inspectorId.toString() !== inspector._id.toString()) {
      return res.status(403).json({ message: 'Not assigned' });
    }
    for (const item of checklist) {
      const { index, answer, comment } = item;
      if (index < 0 || index >= inspection.checklist.length) return res.status(400).json({ message: 'Invalid index' });
      if (answer && !['PASS','FAIL','NA'].includes(answer)) return res.status(400).json({ message: 'Invalid answer' });
      inspection.checklist[index].answer = answer || null;
      if (comment !== undefined) inspection.checklist[index].comment = comment;
    }
    await inspection.save();
    res.status(200).json({ message: 'Checklist updated', checklist: inspection.checklist });
  } catch (error) { next(error); }
};
exports.approveInspection = async (req, res, next) => {
  try {
    const inspection = await Inspection.findById(req.params.id);
    if (!inspection) return res.status(404).json({ message: 'Not found' });
    if (inspection.status !== 'SUBMITTED') return res.status(400).json({ message: 'Inspection not submitted' });
    inspection.status = 'APPROVED';
    inspection.adminStatus = 'APPROVED';
    await inspection.save();
    getSocket().emit('inspection_approved', { inspectionId: inspection._id });
    res.status(200).json({ message: 'Approved' });
  } catch (error) { next(error); }
};
exports.rejectInspection = async (req, res, next) => {
  try {
    const inspection = await Inspection.findById(req.params.id);
    if (!inspection) return res.status(404).json({ message: 'Not found' });
    if (inspection.status !== 'SUBMITTED') return res.status(400).json({ message: 'Inspection not submitted' });
    inspection.status = 'REJECTED';
    inspection.adminStatus = 'REJECTED';
    await inspection.save();
    res.status(200).json({ message: 'Rejected' });
  } catch (error) { next(error); }
};
exports.escalateInspection = async (req, res, next) => {
  try {
    const inspection = await Inspection.findById(req.params.id);
    if (!inspection) return res.status(404).json({ message: 'Not found' });
    inspection.adminStatus = 'ESCALATED';
    await inspection.save();
    getSocket().emit('critical_alert', { inspectionId: inspection._id });
    res.status(200).json({ message: 'Escalated' });
  } catch (error) { next(error); }
};
