const express = require('express');
const { getCameras, getCameraById, createCamera, updateCamera, deleteCamera } = require('../controllers/cctvController');
const { protect } = require('../middleware/authMiddleware');
const { roleMiddleware } = require('../middleware/roleMiddleware');
const router = express.Router();
router.use(protect);
router.use(roleMiddleware('ADMIN'));
router.route('/').get(getCameras).post(createCamera);
router.route('/:id').get(getCameraById).put(updateCamera).delete(deleteCamera);
module.exports = router;
